### ISSUE TITLE
Any update on an example for implementaton

### ISSUE THREAD

**Issue by SaabirMohamed** [Dahkenangnon/flutter_feathersjs.dart#1]
Any update on an example for implementaton

**Comment by Dahkenangnon** [comment]
> Any update on an example for implementaton

Hi, Dear @SaabirMohamed 

I'm working on example.
You can checkout the project documentation site from: https://dahkenangnon.github.io/flutter_feathersjs.dart/

NB: An example app will be available next week.
🚀 🐦

**Comment by Dahkenangnon** [comment]
If you have any question, feel free to participate to the discussion here: https://github.com/Dahkenangnon/flutter_feathersjs.dart/discussions/3#discussion-1232961

**Comment by SaabirMohamed** [comment]
this is great thanks! I will check it out

**Comment by Dahkenangnon** [comment]
Nice, this issue will be close. Feel free to open an other or create discussion.
