### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by kidandcat** [Dahkenangnon/flutter_feathersjs.dart#17]
Does this feathersjs client support Flutter Web target?

**Comment by Dahkenangnon** [comment]
Hello @kidandcat 

Yes, just enjoy it.

See the the docs at: https://dahkenangnon.github.io/flutter_feathersjs.dart/

**Comment by Dahkenangnon** [comment]
For any issue, don't hesitate

**Comment by kidandcat** [comment]
thanks!
