### ISSUE TITLE
[New Features Plans] Some awesome feature are coming for this package user

### ISSUE THREAD

**Issue by Dahkenangnon** [Dahkenangnon/flutter_feathersjs.dart#19]
## :green_circle: New features

These features are planned for from now to June 2022.

More description will be push this weekend to explain in more details these features which are coming.
But before all, i want to know your point of view, would you like these features ?

- [x] Going to null safety ( https://github.com/Dahkenangnon/flutter_feathersjs.dart/discussions/29 )
- [x] Update documentation
- [x] Testable version of flutter web
- [x] Testable version of flutter desktop
- [x] Add feathers services like api 
- [x] Add authentication client 
- [x] Update demo app to sound null safety

At the end, this package will be your very cool and very serious choice for flutter mobile app if you like using feathers js rest+realtime api.

**Comment by humbugz** [comment]
_Add offline database support
Add synchronization with remote api_

Seem like they'd be ideal!

**Comment by Dahkenangnon** [comment]
> _Add offline database support Add synchronization with remote api_
> 
> Seem like they'd be ideal!

Thank @humbugz  for using this package.
Thank for your reply.

These features are will be available from now to June 2022 lately.

For any suggestions to improve this package, feel free to create a PR

Chee

**Comment by Dahkenangnon** [comment]
Please let me know if you are interested in these features please.

**Comment by dmatuschek** [comment]
> _Add offline database support Add synchronization with remote api_
> 
> Seem like they'd be ideal!

These would be incredible features :rocket: 
If it isn't possible yet: Allow developers to initialize the Rest and Socket config separately (especially the baseUrl) or as the official feathers-client, let the developer decide whether to work only with socket or rest. An example:

I host a Feathers API behind a reverse proxy at https://my-app.com/api - then the socket configuration would still need the https://my-app.com/ because the baseUrl of https://my-app.com/api would imply that the socket.io uses "api" as the namespace. On the other hand, the Rest API would still need the https://my-app.com/api as baseUrl. Therefore this should be configurable separately. 

An idea for this could be, to initialize the package in flutter like the feathers package. Therefore to keep the mentality of feathers to be independent of the transportation mode and the package is easily extendable for the Primus Client for example.

A example initialization could be:

## Socket.io
```DART
import 'package:flutter_feathersjs/flutter_feathersjs.dart';
import 'package:socket_io_client/socket_io_client.dart' as IO;

FlutterFeathersjs client = FlutterFeathersjs();
IO.Socket io = IO.io(baseUrl)

client.configure(FlutterFeathersjs.socket(io));

client.service('messages').create({
  text: 'A new message'
});
```

## Rest (With Dio)
```DART
import 'package:flutter_feathersjs/flutter_feathersjs.dart';
import 'package:dio/dio.dart';

FlutterFeathersjs client = FlutterFeathersjs();
Dio dio = Dio(BaseOptions(
      baseUrl: baseUrl,
      headers: extraHeaders
));

client.configure(FlutterFeathersjs.rest(dio));

client.service('messages').create({
  text: 'A new message'
});

```

**Comment by Dahkenangnon** [comment]
> > _Add offline database support Add synchronization with remote api_
> > Seem like they'd be ideal!
> 
> These would be incredible features 🚀 If it isn't possible yet: Allow developers to initialize the Rest and Socket config separately (especially the baseUrl) or as the official feathers-client, let the developer decide whether to work only with socket or rest. An example:
> 
> I host a Feathers API behind a reverse proxy at https://my-app.com/api - then the socket configuration would still need the https://my-app.com/ because the baseUrl of https://my-app.com/api would imply that the socket.io uses "api" as the namespace. On the other hand, the Rest API would still need the https://my-app.com/api as baseUrl. Therefore this should be configurable separately.
> 
> An idea for this could be, to initialize the package in flutter like the feathers package. Therefore to keep the mentality of feathers to be independent of the transportation mode and the package is easily extendable for the Primus Client for example.
> 
> A example initialization could be:
> 
> ## Socket.io
> ```dart
> import 'package:flutter_feathersjs/flutter_feathersjs.dart';
> import 'package:socket_io_client/socket_io_client.dart' as IO;
> 
> FlutterFeathersjs client = FlutterFeathersjs();
> IO.Socket io = IO.io(baseUrl)
> 
> client.configure(FlutterFeathersjs.socket(io));
> 
> client.service('messages').create({
>   text: 'A new message'
> });
> ```
> 
> ## Rest (With Dio)
> ```dart
> import 'package:flutter_feathersjs/flutter_feathersjs.dart';
> import 'package:dio/dio.dart';
> 
> FlutterFeathersjs client = FlutterFeathersjs();
> Dio dio = Dio(BaseOptions(
>       baseUrl: baseUrl,
>       headers: extraHeaders
> ));
> 
> client.configure(FlutterFeathersjs.rest(dio));
> 
> client.service('messages').create({
>   text: 'A new message'
> });
> ```

:rocket:
Greate idea

You should notice i create an issue https://github.com/Dahkenangnon/flutter_feathersjs.dart/issues/28  .

I'll add this possibility before finishing the above planned features and create a new release for it.


Thank @dmatuschek
