### ISSUE TITLE
Authentication Breaking Due to Casting Error on Future

### ISSUE THREAD

**Issue by humbugz** [Dahkenangnon/flutter_feathersjs.dart#22]
I'm not entirely sure what changed within my project (new packed updated perhaps?), but Flutter Feathers started failing on authentication due to a casting error.

Tracked the problem down to feathersjs.dart, line 61:

` //Then auth with jwt socketio`
`        bool isAuthenticated = await (scketio.authWithJWT() as  FutureOr<bool>);`

Cast exception is thrown as it is expecting `Future<dynamic>`. 

If I modify the code to use dynamic, it works:
`        bool isAuthenticated = await (scketio.authWithJWT() as  Future<dynamic>);`

Update: It's due to my project updating from 3.0.0 of the package to 4.0.2: I didn't have a version specified so it updated unintentionally. Seems there is an issue in 4.0.2?

**Comment by Dahkenangnon** [comment]
Does the exception gone when you downgrade to v3.0.0, the exception  ?

Please, can use fill all the stacktrace of the error please.

**Comment by humbugz** [comment]
Yes, the problem is resolved by reverting to v3.0.0.

After the REST authentication is complete and it attempts to authenticate via Sockets:

The error: `type 'Future<dynamic>' is not a subtype of type 'FutureOr<bool>' in type cast`

Occurs because of: `/lib/src/feathersjs.dart`
Line 61: 
`bool isAuthenticated = await (scketio.authWithJWT() as FutureOr<bool>);`

The future needs to be `Future<dynamic>`. 

With that update made 4.0.2 works as expected.

**Comment by Dahkenangnon** [comment]
Ok.

This will fix quickly and a new patch version will be published to solve the problem.

Thank for using this package and feel free to make contribution  by  voting to new coming features 
at https://github.com/Dahkenangnon/flutter_feathersjs.dart/issues/19

thank @humbugz

**Comment by Dahkenangnon** [comment]
Does your app use the dart null safety feature?

**Comment by humbugz** [comment]
Thanks for the quick-fix and for your package!

Re: Null safety: unfortunately not yet, no.

**Comment by Dahkenangnon** [comment]
> Thanks for the quick-fix and for your package!
> 
> Re: Null safety: unfortunately not yet, no.

Ok. Thank.

**Comment by Dahkenangnon** [comment]
The other thing to know is that the package version is updated with pub.dev not here on GitHub. The last version on the pub is 4.0.3, not 4.0.2 ?

Have you tried this version? Or do you use the code from Github ?

The Github version build will be remove to focus on pub.dev release only.

**Comment by humbugz** [comment]
I'd used pub.dev, not Github directly. It's possible it was 4.0.3 that was installed - sorry, I'm not 100% sure.

**Comment by Dahkenangnon** [comment]
> I'd used pub.dev, not Github directly. It's possible it was 4.0.3 that was installed - sorry, I'm not 100% sure.


Voilà. It's 4.0.3 which were installed as you did't specify a version (in that case the last version is installed).


Happy hacking FeathersJs+Flutter to :rocket:

Don't miss the documentation at: https://dahkenangnon.github.io/flutter_feathersjs.dart/ for in-depth details.

**Comment by humbugz** [comment]
Thanks, yeah that makes sense. I'd looked over the Github releases at one point, likely where I got the 4.0.2 version number instead. 

Other than the unintended upgrade that broke, I've been using Flutter Feathers for a few months now - love it!
