### ISSUE TITLE
i need hendel Socket.io events !! 

### ISSUE THREAD

**Issue by biloo-dev** [Dahkenangnon/flutter_feathersjs.dart#43]
**  Thanks for this package, @Dahkenangnon ♥♥
I have a different approach to connecting to the server.
Every device must connect to its own server.
if this address and port do not connect, show the client an error to check, and dispense with it so that auto-reconnecting does not occur;

i want ti handle this evnt whene `socket = FlutterFeathersjs()..init(baseUrl: baseUrl);`

![2022-06-14_015805](https://user-images.githubusercontent.com/37638323/173471541-71071038-8f8a-40a7-b060-dabb1a3a72a4.png)

this is my Ui Project -> 

![2022-06-14_020413](https://user-images.githubusercontent.com/37638323/173471939-7fa646f2-00c6-4954-9c79-2649c950d375.png)

**Comment by Dahkenangnon** [comment]
Hey @biloo-dev 

This is want i think you're talking:

You whould appreciate if you can set in configuration auto reconnection of Socket.io client


If yes, this should be fixed in the next major version (many customs configurations will be available among them, this one).


If i misunderstand you, please, give me more details.

Thank

**Comment by biloo-dev** [comment]
You've got great ideas, and I'm looking forward to seeing what you do next. ♥ ♥ ♥

**Comment by biloo-dev** [comment]
any updates please ??

**Comment by Dahkenangnon** [comment]
Yes ... As I mentioned, it's for soon

**Comment by Dahkenangnon** [comment]
> any updates please ??


**UPDATE AVAILABLE 🚀 ** 

Please try the recent pre-release https://pub.dev/packages/flutter_feathersjs/versions/4.1.0-dev

For any discusion about this prelease, please use disccusion under the release. https://github.com/Dahkenangnon/flutter_feathersjs.dart/discussions/46
