### ISSUE TITLE
socket queries

### ISSUE THREAD

**Issue by semihpolat** [Dahkenangnon/flutter_feathersjs.dart#7]
Hello from Turkey; Firstly great job. How can we make socket queries with this library? I check the docs there is nothing about it

**Comment by Dahkenangnon** [comment]
❤️ Yes @semihpolat 
Thank for your comment. The doc for socketio queries will be available on this weekend.

A tiny application will available.
Thank

**Comment by Dahkenangnon** [comment]
The package is now ready to use.

You can find response with below: 
_____________________________________

See release informations:  https://github.com/Dahkenangnon/flutter_feathersjs.dart/releases/tag/V3.0.0

See the full documentation: https://dahkenangnon.github.io/flutter_feathersjs.dart/

Grab now the package on your flutter app: https://pub.dev/packages/flutter_feathersjs


So, this issue will be closed
